-- MySQL Script generated by MySQL Workbench
-- 04/29/16 13:57:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gkoutr2db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gkoutr2db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gkoutr2db` DEFAULT CHARACTER SET latin1 ;
USE `gkoutr2db` ;

-- -----------------------------------------------------
-- Table `gkoutr2db`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Employee` (
  `employee_id` CHAR(8) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `Minit` CHAR(1) NULL,
  `last_name` VARCHAR(45) NULL,
  `gender` CHAR(1) NULL,
  `address` VARCHAR(45) NULL,
  `phone_num` CHAR(10) NULL,
  `base_pay` DOUBLE NULL,
  `postion` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `isManager` TINYINT(1) NULL,
  PRIMARY KEY (`employee_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Customer` (
  `Customer_ID` CHAR(8) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `Minit` CHAR(1) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `sum_orders` DOUBLE NULL,
  `reward_amt` DOUBLE NULL,
  PRIMARY KEY (`Customer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Inventory` (
  `item_ID` CHAR(5) NOT NULL,
  `item_name` VARCHAR(45) NULL,
  `brand` VARCHAR(45) NULL,
  `catagory` VARCHAR(45) NULL,
  `gender` CHAR(1) NULL,
  `price` DOUBLE NULL,
  PRIMARY KEY (`item_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Cart` (
  `cust_id` CHAR(8) NOT NULL,
  `total` DOUBLE NULL,
  `emp_id` CHAR(8) NULL,
  `item_id` CHAR(5) NULL,
  PRIMARY KEY (`cust_id`),
  INDEX `emp_id_idx` (`emp_id` ASC),
  INDEX `item_id_idx` (`item_id` ASC),
  CONSTRAINT `cust_id`
    FOREIGN KEY (`cust_id`)
    REFERENCES `gkoutr2db`.`Customer` (`Customer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gkoutr2db`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `item_id`
    FOREIGN KEY (`item_id`)
    REFERENCES `gkoutr2db`.`Inventory` (`item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Goals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Goals` (
  `emp_id` CHAR(8) NOT NULL,
  `total_sales` DOUBLE NULL,
  `curr_year` DOUBLE NULL,
  `lat_year` DOUBLE NULL,
  PRIMARY KEY (`emp_id`),
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gkoutr2db`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Commission` (
  `emp_id` CHAR(8) NOT NULL,
  `shoes` DOUBLE NULL,
  `apperal` DOUBLE NULL,
  `accessories` DOUBLE NULL,
  `total_commission` DOUBLE NULL,
  PRIMARY KEY (`emp_id`),
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `gkoutr2db`.`Employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gkoutr2db`.`Size`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gkoutr2db`.`Size` (
  `item-id` CHAR(5) NOT NULL,
  `size` DOUBLE NULL,
  `quanitity` INT NULL,
  PRIMARY KEY (`item-id`),
  CONSTRAINT `item_id`
    FOREIGN KEY (`item-id`)
    REFERENCES `gkoutr2db`.`Inventory` (`item_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
